# Generated by Django 4.2 on 2023-06-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0009_alter_produkitem_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='gambar',
            field=models.ImageField(upload_to='product_pics'),
        ),
    ]
