# Generated by Django 4.2 on 2023-06-06 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0011_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact'},
        ),
    ]
