# Generated by Django 4.2 on 2023-06-06 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toko', '0012_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_komentar', models.TextField()),
                ('tanggal_komentar', models.DateTimeField(auto_now_add=True)),
                ('produk_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentars', to='toko.produkitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='produkitem',
            name='komentar',
            field=models.ManyToManyField(blank=True, related_name='produk_items', to='toko.komentar'),
        ),
    ]
